power <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
power$Date <- as.Date(power$Date, format = "%d/%m/%Y")
data <- subset(power, power$Date == "2007-02-01" | power$Date == "2007-02-02")
hist(data$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png", height = 480, width = 480)
dev.off()
