Sys.setlocale(category = "LC_TIME", "English")
power <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
power$Date <- as.Date(power$Date, format = "%d/%m/%Y")
data <- subset(power, power$Date == "2007-02-01" | power$Date == "2007-02-02")
data$datetime <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
with(data, plot(datetime, Sub_metering_1, type = "l", ylab = "Energy Sub metering", xlab = ""))
with(data, points(datetime, Sub_metering_2, type = "l", col = "red"))
with(data, points(datetime, Sub_metering_3, type = "l", col = "blue"))
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png", height = 480, width = 480)
dev.off()
